#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/llama_env.sh"

configure_embedding_env() {
  ROOT_DIR="$(llama_root_dir)"
  ENV_FILE="${ENV_FILE:-${ROOT_DIR}/.env}"
  load_llama_env_file "$ENV_FILE"

  EMBEDDING_LLAMA_CPP_BIN="$(expand_llama_path "${EMBEDDING_LLAMA_CPP_BIN:-${LLAMA_CPP_BIN:-~/tools/llama.cpp/build/bin/llama-server}}")"
  EMBEDDING_SERVER_HOST="${EMBEDDING_SERVER_HOST:-127.0.0.1}"
  EMBEDDING_SERVER_PORT="${EMBEDDING_SERVER_PORT:-8081}"
  EMBEDDING_SERVER_MODEL_REPO="${EMBEDDING_SERVER_MODEL_REPO:-ggml-org/embeddinggemma-300M-qat-q4_0-GGUF}"
  EMBEDDING_SERVER_MODEL_PATH="${EMBEDDING_SERVER_MODEL_PATH:-}"
  EMBEDDING_SERVER_ALIAS="${EMBEDDING_SERVER_ALIAS:-embeddinggemma-300m}"
  EMBEDDING_SERVER_CTX_SIZE="${EMBEDDING_SERVER_CTX_SIZE:-2048}"
  EMBEDDING_SERVER_THREADS="${EMBEDDING_SERVER_THREADS:-8}"
  EMBEDDING_SERVER_BATCH_SIZE="${EMBEDDING_SERVER_BATCH_SIZE:-2048}"
  EMBEDDING_SERVER_UBATCH_SIZE="${EMBEDDING_SERVER_UBATCH_SIZE:-512}"
  EMBEDDING_SERVER_GPU_LAYERS="${EMBEDDING_SERVER_GPU_LAYERS:-auto}"
  EMBEDDING_SERVER_FLASH_ATTN="${EMBEDDING_SERVER_FLASH_ATTN:-true}"
  EMBEDDING_SERVER_EXTRA_ARGS="${EMBEDDING_SERVER_EXTRA_ARGS:-}"
  EMBEDDING_SERVER_PID_FILE="$(expand_llama_path "${EMBEDDING_SERVER_PID_FILE:-/tmp/offline-hub-embedding-server.pid}")"
  EMBEDDING_SERVER_SHUTDOWN_TIMEOUT_SECONDS="${EMBEDDING_SERVER_SHUTDOWN_TIMEOUT_SECONDS:-15}"
  EMBEDDING_BASE_URL="${EMBEDDING_BASE_URL:-http://${EMBEDDING_SERVER_HOST}:${EMBEDDING_SERVER_PORT}/v1}"
  EMBEDDING_MODEL="${EMBEDDING_MODEL:-${EMBEDDING_SERVER_ALIAS}}"
}

embedding_api_available() {
  curl -fsS --max-time 2 "${EMBEDDING_BASE_URL}/models" >/dev/null 2>&1
}
